// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2w_UVPVrIBzUn9ol16EyqjGjei9RidUM',
    appId: '1:1072106741288:web:ea409e22229f42094e1f1d',
    messagingSenderId: '1072106741288',
    projectId: 'levelx-interview',
    authDomain: 'levelx-interview.firebaseapp.com',
    storageBucket: 'levelx-interview.appspot.com',
    measurementId: 'G-Z9QPV0PPF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAysUyjwpCHXihGqbOc2fksI64sQ6sOrJs',
    appId: '1:1072106741288:android:e802b02d0192e6634e1f1d',
    messagingSenderId: '1072106741288',
    projectId: 'levelx-interview',
    storageBucket: 'levelx-interview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxIz1NaO9ausPvyVfD6U_k7yEBo0egHYY',
    appId: '1:1072106741288:ios:d8175bc027d1d5ac4e1f1d',
    messagingSenderId: '1072106741288',
    projectId: 'levelx-interview',
    storageBucket: 'levelx-interview.appspot.com',
    iosBundleId: 'com.example.levelxInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxIz1NaO9ausPvyVfD6U_k7yEBo0egHYY',
    appId: '1:1072106741288:ios:9629f04a0881be524e1f1d',
    messagingSenderId: '1072106741288',
    projectId: 'levelx-interview',
    storageBucket: 'levelx-interview.appspot.com',
    iosBundleId: 'com.example.levelxInterview.RunnerTests',
  );
}
